spring:
  application:
    name: minadevelop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minadevelop2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 2270398619
    ##配置hikari数据源
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #????
        min-idle: 0
        # ????
        max-idle: 5
        #????????(???????)
        max-wait: -1
        #?????
        max-active: 8
        #??????
    timeout: 10000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
#配置日志地址
logging:
  config: classpath:log/logback_dev.xml
# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.miku.minadevelop.*.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      table-prefix: cc_
      logic-delete-field: isValid
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    description: "`我是测试`,**你知道吗**# aaa"
#    email: xiaoymin@foxmail.com
#    concat: weilai
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.miku.minadevelop.modules
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  sso:
    auth-url: http://127.0.0.1:8080/user/doLogin
    slo-url:
# 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中， 这里配置redis的key的前缀,默认是captcha:slider
  prefix: captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 100000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 200000
  # 使用加载系统自带的资源， 默认是 false
  init-default-resource: false
  cache:
    # 缓存控制， 默认为false不开启
    enabled: true
    # 验证码会提前缓存一些生成好的验证数据， 默认是20
    cacheSize: 20
    # 缓存拉取失败后等待时间 默认是 5秒钟
    wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    period: 2000
  secondary:
    # 二次验证， 默认false 不开启
    enabled: false
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    keyPrefix: "captcha:secondary"
minadevelop:
  fileurl: D:/nginx-1.26.1/file/
  weburl: http://localhost/upload/
pcr:
  name: 咖啡馆
  ts: 1722913722520
  nonce: 40d908db-47d6-4592-a779-588963028266
  appkey: f07288b7ef7645c7a3997baf3d208b62
  sign: 91f14179fd28b87837d03c157961e3d5
  Cookie: SESSDATA=319e5dce%2C1738400231%2C56351%2A81CjAnUuFMIECEgHodX-upHeHVz89LnN0pSNSrSwaKuFdqz72JazQXoSvZd9cMT4oZrw8SVlhwT0pwam9yUE8xd0FUOTllNC1BWVNUeUlEYVMzY3ExS1B2dHRTTEllUEcyUW5lQVllcndvWFJydDE2Z2h2aW00VEY5X09SZUhIN0wtaGd5bVhtODV3IIEC